configure: fix missing `floor` on fedora40
Problem: The build of optparse tests fails on fedora 40 due to an
undefined reference to `floor`.

Add a check for `floor` in libm to configure.